### PR TITLE
Compile on windows

### PR DESCRIPTION
**Pull request by moble**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by moble** [comment]
@conda-forge-admin, please rerender

**Comment by moble** [comment]
@conda-forge/core Is there any way to use gcc on windows — preferably on all python versions, but especially on newer ones?  This code is incompatible with MSVC, and I thought it would just take adding

```yaml
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}          # [win]
```

but I keep getting a linker error on windows because [it can't find `msvcr140`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=199725&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=399).  Googling, it looks like `vcruntime140` may be the right library to link, but this seems likely to be a configuration issue in conda-build or whatever runs it on azure.  (I also [asked about this](https://gitter.im/conda/conda-build?at=5f3fe4c789cf2d584b68aa46) on gitter but haven't gotten a response yet.)

**Comment by isuruf** [comment]
@moble, I think it would be easier to get it working with MSVC. Otherwise, you'll have to compile fftw with mingw too.
What's the error with MSVC?

**Comment by moble** [comment]
I would really appreciate any help you could give me on that.

Basically, it comes down to MSVC not supporting C99 complex types, and then the underlying code needing to use the `fftw_complex` type based on that.  (Just casting between `complex` and `fftw_complex` can give segfaults.)  I tried many hacks on the underlying code, so there have been different errors at different times.  But the original error is [this:](https://github.com/moble/spinsfast/runs/1032071323?check_suite_focus=true#step:5:269)

```
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2061: syntax error: identifier 'fftw_complex'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2059: syntax error: ';'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2143: syntax error: missing ')' before '*'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2081: 'fftw_complex': name in formal parameter list illegal
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2143: syntax error: missing '{' before '*'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2143: syntax error: missing ';' before '*'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2059: syntax error: 'type'
C:\Miniconda\envs\test/Library/include\fftw3.h(457): error C2059: syntax error: ')'
```

After hacking around on it *a lot* (~81 commits worth), the closest I came with MSVC was giving me [this:](https://github.com/moble/spinsfast/runs/1006040913?check_suite_focus=true#step:4:103)

```
code\spinsfast_backward_Gmm.c(50): error C2106: '=': left operand must be l-value
code\spinsfast_backward_Gmm.c(59): error C2440: 'function': cannot convert from '_Fcomplex' to '_Dcomplex'
code\spinsfast_backward_Gmm.c(59): warning C4024: 'cpow': different types for formal and actual parameter 1
code\spinsfast_backward_Gmm.c(59): error C2440: 'function': cannot convert from 'int' to '_Dcomplex'
code\spinsfast_backward_Gmm.c(59): warning C4024: 'cpow': different types for formal and actual parameter 2
code\spinsfast_backward_Gmm.c(59): error C2440: '=': cannot convert from '_Dcomplex' to 'fftw_complex'
```

which is pointing to [this code](https://github.com/moble/spinsfast/blob/a5b74abe8c554d8f03d8509f8aa38158dff6a0b6/code/spinsfast_backward_Gmm.c#L59).  (Apparently MSVC defines `I` to be `_Fcomplex` — but redefining it leads to other problems.)

**Comment by isuruf** [comment]
If it's only that error, you can try,
```C
#ifdef _MSC_VER
_Dcomplex res = cpow(_Dcomplex{0.0, 1.0}, _Dcomplex{m, 0.0});
Ito[m] = {creal(res), cimag(res)};
#else
Ito[m] = cpow(I,m);
#endif
```

**Comment by moble** [comment]
Thanks for the suggestion, but that doesn't work either; it says `error C2059: syntax error: '{'`.

I've cut all this down to a [minimal example project](https://github.com/moble/msvc_test/blob/master/simple.c), with the simplest code I can think of and various ways of using fftw_complex in MSVC.  Every way I can think of using this — compiling as C++, using the MSVC complex header, not using it, etc. — still breaks, except one.  Basically, the only way I can make it compile (which I'm just guessing means it actually works) is to pass a flag asking `fftw3` to just do

    typedef double fftw_complex[2]

and then assign elements of `fftw_complex` arrays with statements like

    Ito[m][0] = creal(res);
    Ito[m][1] = cimag(res);

And rewriting the whole `spinsfast` code to do this is not something I want to take on right now.

**Comment by isuruf** [comment]
A hack would be to do,
```
#include <fftw3.h>
#ifdef _MSC_VER
#define fftw_complex _Dcomplex
#endif
```

**Comment by moble** [comment]
Nope, [same error](https://github.com/moble/msvc_test/runs/1038354838?check_suite_focus=true#step:4:45).  Anything like `Ito[m] = {0.0, 0.0};` just causes that syntax error.  :/

**Comment by isuruf** [comment]
`Ito[m] = (fftw_complex){0.0, 0.0};` should work though

**Comment by isuruf** [comment]
If you can make the files C++, then 
```
#define fftw_complex std::complex<double>
```
should make `Ito[m] = {0.0, 0.0};` work.

**Comment by moble** [comment]
Ah!  You're right, `(fftw_complex){0.0, 0.0}` does.  This might be an easy enough change for me to make to the codebase.  Thanks for your help!

**Pull request closed without merging**
